
import React,{useState} from 'react';import {View,Text,ScrollView,TextInput,TouchableOpacity,StyleSheet} from 'react-native';import {Colors} from '../theme/colors';import {MacroDonutRing} from '../components/MacroDonutRing';import {PastelCard} from '../components/PastelCard';import {getLastResult} from './ScannerScreen';import {saveFood} from '../storage/storage';import {todayKey} from '../utils/calc';
export function FoodDetailScreen({navigation}:any){
 const orig=getLastResult(); const [name,setName]=useState(orig?.foodName||'Meal'); const [weight,setWeight]=useState(orig?.estimatedWeightGrams||240); const [sizeLabel,setSizeLabel]=useState('Medium'); const [showPicker,setShowPicker]=useState(false);
 if(!orig) return <View style={{flex:1,alignItems:'center',justifyContent:'center'}}><Text>No result</Text></View>;
 const factor=weight/(orig.estimatedWeightGrams||240); const scaled={...orig,estimatedWeightGrams:weight,calories:orig.calories*factor,proteinG:orig.proteinG*factor,carbsG:orig.carbsG*factor,fatsG:orig.fatsG*factor,sugarG:orig.sugarG*factor,cholesterolMg:orig.cholesterolMg*factor,fiberG:orig.fiberG*factor};
 const addToMeal=async(mealType:any)=>{await saveFood({id:Date.now().toString(),name,photoUri:orig.photoUri,base64:orig.base64,mealType,dateKey:todayKey(),weightGrams:scaled.estimatedWeightGrams,calories:scaled.calories,proteinG:scaled.proteinG,carbsG:scaled.carbsG,fatsG:scaled.fatsG,sugarG:scaled.sugarG,cholesterolMg:scaled.cholesterolMg,fiberG:scaled.fiberG,vitamins:scaled.vitaminsSummary,loggedAt:Date.now()}); navigation.reset({index:0,routes:[{name:'MainTabs'}]});};
 return (<View style={{flex:1,backgroundColor:'#121212'}}><View style={{height:340,backgroundColor:'#2A2A2A',alignItems:'center',justifyContent:'center'}}><Text style={{fontSize:48}}>🍱</Text><TouchableOpacity onPress={()=>navigation.goBack()} style={{position:'absolute',top:48,left:16}}><Text style={{color:'#FFF',fontSize:22}}>←</Text></TouchableOpacity></View><View style={{flex:1,backgroundColor:'#FFF',borderTopLeftRadius:28,borderTopRightRadius:28,marginTop:-24}}><ScrollView contentContainerStyle={{padding:20}}>
  <TextInput value={name} onChangeText={setName} style={{borderWidth:1,borderColor:'#EEE',borderRadius:12,padding:12,fontWeight:'800',fontSize:18}}/>
  <View style={{flexDirection:'row',alignItems:'center',marginTop:16}}><MacroDonutRing calories={Math.round(scaled.calories)} protein={scaled.proteinG} carbs={scaled.carbsG} fats={scaled.fatsG} size={110} stroke={10}/><View style={{marginLeft:16,gap:8}}><View style={{backgroundColor:Colors.proteinFill,paddingHorizontal:12,paddingVertical:8,borderRadius:20,flexDirection:'row',gap:6}}><View style={{width:6,height:6,borderRadius:3,backgroundColor:Colors.proteinText}}/><Text style={{fontSize:11,color:Colors.proteinText}}>Proteins</Text><Text style={{fontWeight:'800',color:Colors.proteinText,fontSize:12}}>{Math.round(scaled.proteinG)} g</Text></View><View style={{backgroundColor:Colors.carbsFill,paddingHorizontal:12,paddingVertical:8,borderRadius:20,flexDirection:'row',gap:6}}><View style={{width:6,height:6,borderRadius:3,backgroundColor:Colors.carbsText}}/><Text style={{fontSize:11,color:Colors.carbsText}}>Carbs</Text><Text style={{fontWeight:'800',color:Colors.carbsText,fontSize:12}}>{Math.round(scaled.carbsG)} g</Text></View><View style={{backgroundColor:Colors.fatsFill,paddingHorizontal:12,paddingVertical:8,borderRadius:20,flexDirection:'row',gap:6}}><View style={{width:6,height:6,borderRadius:3,backgroundColor:Colors.fatsText}}/><Text style={{fontSize:11,color:Colors.fatsText}}>Fats</Text><Text style={{fontWeight:'800',color:Colors.fatsText,fontSize:12}}>{Math.round(scaled.fatsG)} g</Text></View></View></View>
  <Text style={{fontWeight:'800',fontSize:16,marginTop:20}}>Macros</Text><View style={{height:1,backgroundColor:'#EEE',marginVertical:8}}/>{[{l:'Sugar',v:`${Math.round(scaled.sugarG)} g`},{l:'Cholesterol',v:`${Math.round(scaled.cholesterolMg)} g`},{l:'Fiber',v:`${Math.round(scaled.fiberG)} g`}].map(r=><View key={r.l} style={{flexDirection:'row',justifyContent:'space-between',paddingVertical:6,borderBottomWidth:1,borderColor:'#F5F5F5'}}><Text style={{color:Colors.textSecondary}}>{r.l}</Text><Text style={{fontWeight:'600'}}>{r.v}</Text></View>)}
  <Text style={{fontWeight:'800',fontSize:16,marginTop:16}}>Vitamins</Text><View style={{height:1,backgroundColor:'#EEE',marginVertical:8}}/>{scaled.vitaminsSummary.map((v:string,i:number)=><View key={i} style={{flexDirection:'row',justifyContent:'space-between',paddingVertical:6,borderBottomWidth:1,borderColor:'#F5F5F5'}}><Text style={{color:Colors.textSecondary}}>{v}</Text></View>)}
  <View style={{flexDirection:'row',alignItems:'center',marginTop:20,flexWrap:'wrap',gap:6}}><View><Text style={{fontWeight:'900',fontSize:20}}>{Math.round(weight)}</Text><Text style={{fontSize:12,color:Colors.textSecondary}}>Weight, g</Text></View><TouchableOpacity onPress={()=>{setWeight(orig.estimatedWeightGrams*0.7); setSizeLabel('Small')}} style={[styles.chip,sizeLabel==='Small'&&{backgroundColor:Colors.brand}]}><Text style={{color:sizeLabel==='Small'?'#FFF':'#000'}}>Small 0.7x</Text></TouchableOpacity><TouchableOpacity onPress={()=>{setWeight(orig.estimatedWeightGrams); setSizeLabel('Medium')}} style={[styles.chip,sizeLabel==='Medium'&&{backgroundColor:Colors.brand}]}><Text style={{color:sizeLabel==='Medium'?'#FFF':'#000'}}>Medium 1x</Text></TouchableOpacity><TouchableOpacity onPress={()=>{setWeight(orig.estimatedWeightGrams*1.5); setSizeLabel('Large')}} style={[styles.chip,sizeLabel==='Large'&&{backgroundColor:Colors.brand}]}><Text style={{color:sizeLabel==='Large'?'#FFF':'#000'}}>Large 1.5x</Text></TouchableOpacity></View>
  <TouchableOpacity onPress={()=>setShowPicker(true)} style={{backgroundColor:Colors.brandDark,padding:14,borderRadius:24,alignItems:'center',marginTop:16}}><Text style={{color:'#FFF',fontWeight:'800'}}>+ Add to Meal</Text></TouchableOpacity>
  {showPicker&&<View style={{marginTop:16,gap:8}}><PastelCard title="Breakfast" subtitle="Morning" bg={Colors.pastelYellow} emoji="🍳" onPress={()=>addToMeal('BREAKFAST')}/><PastelCard title="Lunch" subtitle="Afternoon" bg={Colors.pastelGreen} emoji="🥗" onPress={()=>addToMeal('LUNCH')}/><PastelCard title="Dinner" subtitle="Evening" bg={Colors.pastelPink} emoji="🍲" onPress={()=>addToMeal('DINNER')}/><PastelCard title="Snacks" subtitle="Anytime" bg={Colors.pastelLavender} emoji="🍎" onPress={()=>addToMeal('SNACK')}/></View>}
 </ScrollView></View></View>)
}
const styles=StyleSheet.create({chip:{paddingHorizontal:10,paddingVertical:6,borderRadius:12,backgroundColor:'#EEE'}})
