
import React,{useEffect,useState,useCallback} from 'react';import {View,Text,ScrollView,TouchableOpacity,StyleSheet} from 'react-native';import {Colors} from '../theme/colors';import {DateStrip} from '../components/DateStrip';import {MacroDonutRing} from '../components/MacroDonutRing';import {MacroPill} from '../components/MacroPill';import {TrendingCard} from '../components/TrendingCard';import {getFoodsByDate,getGoal,getUserName,FoodEntry} from '../storage/storage';import {todayKey} from '../utils/calc';import {useFocusEffect} from '@react-navigation/native';
function genWeek(selectedKey:string){const days=[]; const base=new Date(); base.setDate(base.getDate()-3); const bgColors=[Colors.pastelGreen,Colors.pastelYellow,Colors.pastelPink,Colors.pastelLavender,Colors.pastelMint,Colors.pastelYellow,Colors.pastelPink]; for(let i=0;i<7;i++){const d=new Date(base); d.setDate(base.getDate()+i); const key=d.toISOString().slice(0,10); days.push({key,dayNum:String(d.getDate()),weekDay:d.toLocaleDateString('en',{weekday:'short'}).slice(0,3),isSelected:key===selectedKey,bg:bgColors[i%7]});} return days;}
export function HomeScreen({navigation}:any){
 const [selectedKey,setSelectedKey]=useState(todayKey()); const [days,setDays]=useState(genWeek(todayKey())); const [foods,setFoods]=useState<FoodEntry[]>([]); const [goal,setGoal]=useState<any>(null); const [name,setName]=useState('Jess');
 const load=async()=>{setFoods(await getFoodsByDate(selectedKey)); setGoal(await getGoal()); setName(await getUserName());};
 useFocusEffect(useCallback(()=>{load()},[selectedKey])); useEffect(()=>{setDays(genWeek(selectedKey)); load()},[selectedKey]);
 const totalKcal=foods.reduce((s,f)=>s+f.calories,0); const totalP=foods.reduce((s,f)=>s+f.proteinG,0); const totalC=foods.reduce((s,f)=>s+f.carbsG,0); const totalF=foods.reduce((s,f)=>s+f.fatsG,0); const budget=goal?.calorieBudget||1820; const left=Math.max(0,budget-totalKcal);
 const meals=[{type:'BREAKFAST',label:'Breakfast'},{type:'LUNCH',label:'Lunch'},{type:'DINNER',label:'Dinner'},{type:'SNACK',label:'Snacks'}];
 return (<View style={{flex:1,backgroundColor:Colors.bg}}>
  <View style={{flexDirection:'row',justifyContent:'space-between',paddingHorizontal:16,paddingTop:56,paddingBottom:12}}><Text style={{fontWeight:'900',fontSize:18}}>Welcome {name},</Text><View style={{flexDirection:'row',gap:8}}><View style={{backgroundColor:Colors.brand,paddingHorizontal:10,paddingVertical:4,borderRadius:12}}><Text style={{color:'#FFF',fontWeight:'800',fontSize:12}}>👑 PRO</Text></View><TouchableOpacity onPress={()=>navigation.navigate('Settings')}><Text>⚙️</Text></TouchableOpacity></View></View>
  <ScrollView showsVerticalScrollIndicator={false}>
   <View style={{marginHorizontal:16,backgroundColor:'#2D4A3E',borderRadius:20,padding:16,flexDirection:'row',marginBottom:12}}><View style={{flex:1}}><Text style={{color:'#FFF',fontWeight:'800'}}>Set your weekly goals</Text><TouchableOpacity style={{marginTop:8,backgroundColor:'#FFF',alignSelf:'flex-start',paddingHorizontal:12,paddingVertical:6,borderRadius:8}}><Text style={{fontWeight:'700',fontSize:12}}>Set now</Text></TouchableOpacity></View><Text style={{fontSize:36}}>🏋️‍♀️</Text></View>
   <DateStrip days={days} onSelect={(d)=>setSelectedKey(d.key)}/>
   <View style={[styles.card,{margin:16,flexDirection:'row',padding:18}]}><View style={{flex:1}}><View style={{flexDirection:'row',alignItems:'center'}}><Text>🔥</Text><Text style={{fontSize:28,fontWeight:'900'}}> {Math.round(totalKcal)}</Text><Text style={{fontSize:12,color:Colors.textSecondary}}> Kcal</Text></View><Text style={{fontSize:13,color:Colors.textSecondary}}>{Math.round(left)} Left</Text><Text style={{fontSize:12,color:Colors.textSecondary,marginTop:8}}>{budget} Kcal Budget</Text></View><MacroDonutRing calories={budget} protein={Math.max(1,totalP)} carbs={Math.max(1,totalC)} fats={Math.max(1,totalF)} size={110} stroke={10}/></View>
   <View style={{paddingHorizontal:16,gap:12}}><MacroPill label="Proteins" consumed={totalP} budget={goal?.proteinBudget||137} fill={Colors.proteinText} bg={Colors.proteinFill} icon="🍗"/><MacroPill label="Carbs" consumed={totalC} budget={goal?.carbsBudget||225} fill={Colors.carbsText} bg={Colors.carbsFill} icon="🍞"/><MacroPill label="Fats" consumed={totalF} budget={goal?.fatsBudget||58} fill={Colors.fatsText} bg={Colors.fatsFill} icon="🥑"/></View>
   <View style={{flexDirection:'row',justifyContent:'space-between',paddingHorizontal:16,marginTop:16}}><Text style={{fontWeight:'800'}}>Trending programs</Text><Text style={{color:Colors.textSecondary,fontSize:12}}>See all</Text></View>
   <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{padding:16,gap:10}}><TrendingCard title="Body sculpt program" subtitle="⭐ 4.9 5h 30m"/><TrendingCard title="Sport nutrition" subtitle="⭐ 4.9 3h 30m"/></ScrollView>
   <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{padding:16,gap:10}}>{meals.map(m=>{const items=foods.filter(f=>f.mealType===m.type); const kcal=items.reduce((s,f)=>s+f.calories,0); return (<TouchableOpacity key={m.type} onPress={()=>items.length?navigation.navigate('MealLog',{mealType:m.type,dateKey:selectedKey}):navigation.navigate('Scanner')} style={styles.mealCard}><View style={{width:56,height:56,borderRadius:28,backgroundColor:'#F5F5F5',alignItems:'center',justifyContent:'center'}}><Text style={{fontSize:22}}>{items.length?'🍱':'+'}</Text></View><Text style={{marginTop:6,fontSize:12,fontWeight:'700'}}>{m.label}</Text><Text style={{fontSize:10,color:Colors.textSecondary}}>{items.length?`🔥 ${Math.round(kcal)} Kcal`:'+Add'}</Text></TouchableOpacity>)})}</ScrollView>
   <View style={{margin:16,backgroundColor:'#1B1B1B',borderRadius:20,padding:14,flexDirection:'row',alignItems:'center'}}><View style={{flex:1}}><Text style={{color:'#FFF',fontWeight:'800',fontSize:13}}>🔥 Almost Free Premium!</Text><Text style={{color:'rgba(255,255,255,0.7)',fontSize:12}}>just $0.99 / month</Text></View><Text style={{fontSize:28}}>🥗</Text></View>
  </ScrollView><TouchableOpacity onPress={()=>navigation.navigate('Scanner')} style={{position:'absolute',right:20,bottom:90,width:60,height:60,borderRadius:30,backgroundColor:Colors.brand,alignItems:'center',justifyContent:'center',elevation:4}}><Text style={{fontSize:24,color:'#FFF'}}>📷</Text></TouchableOpacity></View>)
}
const styles=StyleSheet.create({card:{backgroundColor:'#FFF',borderRadius:28,elevation:2},mealCard:{width:82,backgroundColor:'#FFF',borderRadius:20,padding:10,alignItems:'center'}})
