
import React,{useEffect,useState} from 'react';import {View,Text,FlatList,TouchableOpacity,StyleSheet} from 'react-native';import {Colors} from '../theme/colors';import {getFoods,deleteFood,FoodEntry} from '../storage/storage';
export function MealLogScreen({route,navigation}:any){
 const {mealType,dateKey}=route.params; const [foods,setFoods]=useState<FoodEntry[]>([]);
 const load=async()=>{const all=await getFoods(); setFoods(all.filter(f=>f.mealType===mealType && f.dateKey===dateKey));};
 useEffect(()=>{load()},[]);
 return (<View style={{flex:1,backgroundColor:'#FFF',paddingTop:56}}><View style={{paddingHorizontal:16}}><View style={{flexDirection:'row',alignItems:'center',marginBottom:12}}><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={{fontSize:20}}>←</Text></TouchableOpacity><Text style={{fontWeight:'800',fontSize:16,marginLeft:8}}>Order #{mealType} {dateKey}</Text></View>
 <View style={{flexDirection:'row',gap:8}}><TouchableOpacity style={{backgroundColor:'#1B1B1B',paddingHorizontal:12,paddingVertical:8,borderRadius:12}}><Text style={{color:'#FFF',fontSize:12}}>◍ Track order</Text></TouchableOpacity><TouchableOpacity style={{borderWidth:1,borderColor:'#EEE',paddingHorizontal:12,paddingVertical:8,borderRadius:12}}><Text style={{fontSize:12}}>↻ Reschedule</Text></TouchableOpacity></View>
 <View style={{flexDirection:'row',alignItems:'center',marginTop:16}}><View style={{width:40,height:40,borderRadius:20,backgroundColor:Colors.pastelMint,alignItems:'center',justifyContent:'center'}}><Text>🧑‍🍳</Text></View><View style={{marginLeft:10,flex:1}}><Text style={{fontWeight:'700'}}>Thomas Tanner</Text><Text style={{fontSize:12,color:Colors.textSecondary}}>Nutrition Coach</Text></View><View style={{flexDirection:'row',gap:8}}><View style={{width:32,height:32,borderRadius:16,backgroundColor:'#1B1B1B',alignItems:'center',justifyContent:'center'}}><Text style={{color:'#FFF'}}>📞</Text></View><View style={{width:32,height:32,borderRadius:16,backgroundColor:'#EEE',alignItems:'center',justifyContent:'center'}}><Text>💬</Text></View></View></View>
 <Text style={{fontWeight:'800',marginTop:16}}>Your items ({foods.length})</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8,marginTop:8}}><View style={{flexDirection:'row',gap:8}}>{foods.slice(0,4).map(f=><View key={f.id} style={{width:48,height:48,borderRadius:24,backgroundColor:Colors.bg,alignItems:'center',justifyContent:'center'}}><Text>{f.name[0]}</Text></View>)}{foods.length>4&&<View style={{width:48,height:48,borderRadius:24,backgroundColor:'#EEE',alignItems:'center',justifyContent:'center'}}><Text>+{foods.length-4}</Text></View>}</View></ScrollView>
 <Text style={{fontWeight:'800',marginTop:16}}>Meal history</Text>
 <View style={{marginTop:8,gap:12}}><View style={{flexDirection:'row',gap:8}}><View style={{width:20,height:20,borderRadius:10,backgroundColor:Colors.brand,alignItems:'center',justifyContent:'center'}}><Text style={{color:'#FFF',fontSize:10}}>✓</Text></View><View><Text style={{fontWeight:'600',fontSize:13}}>Order created</Text><Text style={{fontSize:11,color:Colors.textSecondary}}>Today</Text></View></View><View style={{flexDirection:'row',gap:8}}><View style={{width:20,height:20,borderRadius:10,backgroundColor:Colors.brand}}/><View><Text style={{fontWeight:'600',fontSize:13}}>Logged {foods.length} items</Text><Text style={{fontSize:11,color:Colors.textSecondary}}>{Math.round(foods.reduce((s,f)=>s+f.calories,0))} kcal total</Text></View></View></View></View>
 <FlatList data={foods} keyExtractor={i=>i.id} contentContainerStyle={{padding:16,gap:10,marginTop:8}} renderItem={({item})=><View style={styles.card}><View style={{width:48,height:48,borderRadius:12,backgroundColor:Colors.proteinFill,alignItems:'center',justifyContent:'center'}}><Text style={{fontWeight:'800'}}>{item.name[0]}</Text></View><View style={{flex:1,marginLeft:12}}><Text style={{fontWeight:'700'}}>{item.name}</Text><Text style={{fontSize:12,color:Colors.textSecondary}}>{Math.round(item.calories)} kcal • P {Math.round(item.proteinG)}g C {Math.round(item.carbsG)}g F {Math.round(item.fatsG)}g</Text></View><TouchableOpacity onPress={async()=>{await deleteFood(item.id); load();}}><Text>🗑️</Text></TouchableOpacity></View>}/>
 </View>)
}
const styles=StyleSheet.create({card:{flexDirection:'row',backgroundColor:Colors.bg,borderRadius:16,padding:12,alignItems:'center'}})
