
import React,{useState} from 'react';import {View,Text,TextInput,TouchableOpacity,ScrollView,StyleSheet} from 'react-native';import {Colors} from '../theme/colors';import {WeightChart} from '../components/WeightChart';import {PastelCard} from '../components/PastelCard';import {calculateBudget,macroBudgets} from '../utils/calc';import {saveGoal} from '../storage/storage';
export function OnboardingScreen({navigation}:any){
 const [step,setStep]=useState(0); const [name,setName]=useState('Jess'); const [startW,setStartW]=useState('82.5'); const [targetW,setTargetW]=useState('79.5'); const [goalType,setGoalType]=useState<'LOSE'|'GAIN'|'MAINTAIN'>('LOSE'); const [activity,setActivity]=useState<'LOW'|'MODERATE'|'HIGH'>('MODERATE'); const [days,setDays]=useState(30);
 const targetDate=new Date(); targetDate.setDate(targetDate.getDate()+days); const label=targetDate.toLocaleDateString('en',{month:'short',day:'numeric'});
 const onStart=async()=>{const budget=calculateBudget(parseFloat(startW),parseFloat(targetW),days,activity); const macros=macroBudgets(budget,goalType); await saveGoal({name,goalType,startWeight:parseFloat(startW),targetWeight:parseFloat(targetW),targetDate:targetDate.getTime(),activityLevel:activity,calorieBudget:budget,proteinBudget:macros.p,carbsBudget:macros.c,fatsBudget:macros.f,waterBudget:2000}); navigation.replace('MainTabs');}
 if(step===0) return (<View style={{flex:1,backgroundColor:Colors.bg,padding:24,paddingTop:80}}><Text style={{fontSize:28,fontWeight:'900'}}>Welcome!{"\n"}What's your name?</Text><TextInput value={name} onChangeText={setName} placeholder="Your name" style={styles.input}/><TouchableOpacity onPress={()=>setStep(1)} style={styles.primaryBtn}><Text style={{color:'#FFF',fontWeight:'800'}}>Continue</Text></TouchableOpacity></View>);
 if(step===1) return (<ScrollView style={{flex:1,backgroundColor:Colors.bg}} contentContainerStyle={{padding:20,paddingTop:60,gap:12}}><Text style={{fontSize:24,fontWeight:'900'}}>Set your goal, {name}</Text><PastelCard title="Lose Weight" subtitle="Burn fat" bg={Colors.pastelMint} emoji="🔥" onPress={()=>setGoalType('LOSE')} selected={goalType==='LOSE'}/><PastelCard title="Gain Muscle" subtitle="Build strength" bg={Colors.pastelYellow} emoji="💪" onPress={()=>setGoalType('GAIN')} selected={goalType==='GAIN'}/><PastelCard title="Maintain" subtitle="Stay fit" bg={Colors.pastelLavender} emoji="⚖️" onPress={()=>setGoalType('MAINTAIN')} selected={goalType==='MAINTAIN'}/><TouchableOpacity onPress={()=>setStep(2)} style={styles.primaryBtn}><Text style={{color:'#FFF',fontWeight:'800'}}>Next</Text></TouchableOpacity></ScrollView>);
 if(step===2) return (<ScrollView style={{flex:1,backgroundColor:Colors.bg}} contentContainerStyle={{padding:20,paddingTop:60,gap:12}}><Text style={{fontSize:24,fontWeight:'900'}}>Your weight</Text><TextInput value={startW} onChangeText={setStartW} keyboardType="numeric" placeholder="Current kg" style={styles.input}/><TextInput value={targetW} onChangeText={setTargetW} keyboardType="numeric" placeholder="Target kg" style={styles.input}/><Text style={{fontWeight:'700'}}>Activity</Text><View style={{flexDirection:'row',gap:8}}>{(['LOW','MODERATE','HIGH'] as const).map(a=><TouchableOpacity key={a} onPress={()=>setActivity(a)} style={[styles.chip,activity===a&&{backgroundColor:Colors.brand}]}><Text style={{color:activity===a?'#FFF':'#000'}}>{a}</Text></TouchableOpacity>)}</View><TouchableOpacity onPress={()=>setStep(3)} style={styles.primaryBtn}><Text style={{color:'#FFF',fontWeight:'800'}}>Preview Plan</Text></TouchableOpacity></ScrollView>);
 return (<ScrollView style={{flex:1,backgroundColor:Colors.bg}} contentContainerStyle={{padding:20,paddingTop:60,alignItems:'center'}}><Text style={{color:Colors.textSecondary,fontSize:18}}>You will reach</Text><Text style={{fontSize:26,fontWeight:'900',color:Colors.brand}}>{targetW} kg by {label}</Text><View style={{marginVertical:20}}><WeightChart startW={parseFloat(startW)} targetW={parseFloat(targetW)} targetLabel={label}/></View><Text style={{fontSize:13,fontWeight:'600',textAlign:'center'}}>90% of users like you lost {Math.abs(parseFloat(startW)-parseFloat(targetW))}kg with our plan</Text><View style={{width:'100%',backgroundColor:Colors.lavender,borderRadius:20,padding:16,flexDirection:'row',marginTop:16}}><View style={{flex:1,gap:6}}><Text>🎯 Goal: {goalType}</Text><Text>🔥 Calorie: {calculateBudget(parseFloat(startW),parseFloat(targetW),days,activity)} kcal</Text><Text>⏰ Duration: {days} days</Text><Text>💧 Water: 2000 ml</Text></View><Text style={{fontSize:48}}>🧍</Text></View><TouchableOpacity onPress={onStart} style={[styles.primaryBtn,{width:'100%',marginTop:24}]}><Text style={{color:'#FFF',fontWeight:'800'}}>Start My Journey</Text></TouchableOpacity></ScrollView>)
}
const styles=StyleSheet.create({input:{backgroundColor:'#FFF',borderRadius:12,padding:14,borderWidth:1,borderColor:'#EEE',marginTop:16},primaryBtn:{backgroundColor:'#0E8F6E',padding:16,borderRadius:16,alignItems:'center',marginTop:24},chip:{paddingHorizontal:14,paddingVertical:8,borderRadius:12,backgroundColor:'#EEE'}})
