
import React,{useState} from 'react';import {View,Text,TouchableOpacity,StyleSheet,ActivityIndicator} from 'react-native';import {CameraView,useCameraPermissions} from 'expo-camera';import * as ImagePicker from 'expo-image-picker';import {analyzeImageBase64} from '../services/openRouter';
let currentResult:any=null; export const getLastResult=()=>currentResult;
export function ScannerScreen({navigation}:any){
 const [permission,requestPermission]=useCameraPermissions(); const [isBarcode,setIsBarcode]=useState(false); const [analyzing,setAnalyzing]=useState(false); const [error,setError]=useState('');
 if(!permission) return <View/>; if(!permission.granted) return <View style={styles.center}><Text>Camera needed</Text><TouchableOpacity onPress={requestPermission} style={styles.btn}><Text style={{color:'#FFF'}}>Grant</Text></TouchableOpacity></View>;
 const handleCapture=async()=>{setAnalyzing(true); setError(''); try{const res=await ImagePicker.launchCameraAsync({base64:true,quality:0.7}); if(res.canceled){setAnalyzing(false); return;} const b64=res.assets[0].base64!; const analysis=await analyzeImageBase64(b64); currentResult={...analysis,base64:b64,photoUri:res.assets[0].uri}; setAnalyzing(false); navigation.navigate('FoodDetail');}catch(e:any){setAnalyzing(false); setError(e.message||'Failed');}};
 return (<View style={{flex:1,backgroundColor:'#000'}}><CameraView style={{flex:1}} facing="back"/><View style={{position:'absolute',top:48,alignSelf:'center',backgroundColor:'rgba(0,0,0,0.6)',paddingHorizontal:16,paddingVertical:8,borderRadius:20}}><Text style={{color:'#FFF',fontSize:13}}>{isBarcode?'Place barcode inside frame':'Place food inside frame'}</Text></View><View style={{position:'absolute',top:'35%',alignSelf:'center',width:280,height:180,borderWidth:2,borderColor:'#FFF',borderRadius:24}}/>
 {analyzing&&<View style={styles.centerAbs}><View style={{backgroundColor:'#FFF',padding:20,borderRadius:16}}><ActivityIndicator size="large" color="#0E8F6E"/><Text style={{marginTop:8}}>Analyzing GLM-4.6V...</Text></View></View>}
 {error!==''&&<View style={styles.centerAbs}><View style={{backgroundColor:'#FFF',padding:16,borderRadius:16,margin:24}}><Text style={{fontWeight:'700'}}>Failed</Text><Text style={{fontSize:12,marginVertical:8}}>{error}</Text><TouchableOpacity onPress={()=>setError('')} style={styles.btn}><Text style={{color:'#FFF'}}>Retry</Text></TouchableOpacity></View></View>}
 <View style={{position:'absolute',bottom:32,width:'100%',alignItems:'center',gap:16}}><View style={{flexDirection:'row',backgroundColor:'#2A2A2A',borderRadius:24,padding:4,gap:8}}><TouchableOpacity onPress={()=>setIsBarcode(false)} style={{backgroundColor:!isBarcode?'#FFF':'transparent',paddingHorizontal:16,paddingVertical:6,borderRadius:20}}><Text style={{color:!isBarcode?'#000':'#FFF',fontWeight:'600'}}>AI Scanner</Text></TouchableOpacity><TouchableOpacity onPress={()=>setIsBarcode(true)} style={{backgroundColor:isBarcode?'#FFF':'transparent',paddingHorizontal:16,paddingVertical:6,borderRadius:20}}><Text style={{color:isBarcode?'#000':'#FFF',fontWeight:'600'}}>Barcode</Text></TouchableOpacity></View><TouchableOpacity onPress={handleCapture} style={{width:72,height:72,borderRadius:36,backgroundColor:'#FFF',alignItems:'center',justifyContent:'center'}}><View style={{width:60,height:60,borderRadius:30,backgroundColor:'#0E8F6E'}}/></TouchableOpacity></View></View>)
}
const styles=StyleSheet.create({center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#FAFAF8'},centerAbs:{position:'absolute',top:0,left:0,right:0,bottom:0,alignItems:'center',justifyContent:'center'},btn:{backgroundColor:'#0E8F6E',paddingHorizontal:16,paddingVertical:8,borderRadius:12,marginTop:8}})
