
import React,{useState,useEffect} from 'react';import {View,Text,TextInput,TouchableOpacity,ScrollView,Alert} from 'react-native';import {Colors} from '../theme/colors';import {getApiKey,setApiKey} from '../services/openRouter';import {getGoal,clearAll} from '../storage/storage';
export function SettingsScreen({navigation}:any){
 const [key,setKey]=useState(''); const [goal,setGoal]=useState<any>(null); const [status,setStatus]=useState('');
 useEffect(()=>{(async()=>{setKey(await getApiKey()||''); setGoal(await getGoal());})()},[]);
 const test=async()=>{setStatus('Testing...'); try{const r=await fetch('https://openrouter.ai/api/v1/models',{headers:{Authorization:`Bearer ${key}`}}); setStatus(r.ok?'✅ Connected!':'❌ Failed');}catch(e:any){setStatus('❌ '+e.message);}};
 return (<ScrollView style={{flex:1,backgroundColor:Colors.bg}} contentContainerStyle={{padding:20,paddingTop:60,gap:16}}><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={{fontSize:20}}>← Settings</Text></TouchableOpacity>
 <View style={{backgroundColor:'#FFF',borderRadius:20,padding:16}}><Text style={{fontWeight:'800'}}>Calorie Budget</Text><Text style={{marginTop:4}}>{goal?.calorieBudget||1820} kcal</Text><Text style={{fontSize:12,color:Colors.textSecondary}}>P {Math.round(goal?.proteinBudget||137)}g • C {Math.round(goal?.carbsBudget||225)}g • F {Math.round(goal?.fatsBudget||58)}g</Text></View>
 <View style={{backgroundColor:'#FFF',borderRadius:20,padding:16,gap:8}}><Text style={{fontWeight:'800'}}>OpenRouter API Key (GLM-4.6V)</Text><TextInput value={key} onChangeText={setKey} placeholder="sk-or-v1-..." secureTextEntry style={{backgroundColor:Colors.bg,borderRadius:12,padding:12,borderWidth:1,borderColor:'#EEE'}}/><View style={{flexDirection:'row',gap:8}}><TouchableOpacity onPress={async()=>{await setApiKey(key); setStatus('Saved!');}} style={{backgroundColor:Colors.brand,paddingHorizontal:16,paddingVertical:8,borderRadius:12}}><Text style={{color:'#FFF'}}>Save</Text></TouchableOpacity><TouchableOpacity onPress={test} style={{backgroundColor:'#000',paddingHorizontal:16,paddingVertical:8,borderRadius:12}}><Text style={{color:'#FFF'}}>Test</Text></TouchableOpacity></View>{status!==''&&<Text style={{fontSize:12,color:Colors.brand}}>{status}</Text>}</View>
 <View style={{backgroundColor:'#FFF',borderRadius:20,padding:16,gap:8}}><Text style={{fontWeight:'800'}}>Data</Text><TouchableOpacity onPress={()=>Alert.alert('Reset','Clear all?',[{text:'Cancel'},{text:'Reset',style:'destructive',onPress:async()=>{await clearAll(); setStatus('Cleared');}}])} style={{backgroundColor:Colors.calorie,padding:12,borderRadius:12,alignItems:'center'}}><Text style={{color:'#FFF'}}>Reset All Data</Text></TouchableOpacity></View>
 <View style={{backgroundColor:Colors.lavender,borderRadius:20,padding:16}}><Text style={{fontWeight:'800'}}>PlatePal RN</Text><Text style={{fontSize:12,color:Colors.textSecondary,marginTop:4}}>Expo SDK 51, pastel grocery UX, delightful cards, smart search, personalized. Local-first.</Text></View></ScrollView>)
}
