
import React,{useEffect,useState} from 'react';import {NavigationContainer} from '@react-navigation/native';import {createNativeStackNavigator} from '@react-navigation/native-stack';import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';import {Text} from 'react-native';import {HomeScreen} from '../screens/HomeScreen';import {CategoriesScreen} from '../screens/CategoriesScreen';import {SearchScreen} from '../screens/SearchScreen';import {ProgressScreen} from '../screens/ProgressScreen';import {SettingsScreen} from '../screens/SettingsScreen';import {ScannerScreen} from '../screens/ScannerScreen';import {FoodDetailScreen} from '../screens/FoodDetailScreen';import {MealLogScreen} from '../screens/MealLogScreen';import {OnboardingScreen} from '../screens/OnboardingScreen';import {hasOnboarded} from '../storage/storage';import {Colors} from '../theme/colors';
const Stack=createNativeStackNavigator(); const Tab=createBottomTabNavigator();
function MainTabs(){return (<Tab.Navigator screenOptions={{headerShown:false,tabBarActiveTintColor:Colors.brand,tabBarStyle:{borderTopLeftRadius:20,borderTopRightRadius:20,height:70}}}><Tab.Screen name="HomeTab" component={HomeScreen} options={{tabBarLabel:'Home',tabBarIcon:()=><Text>🏠</Text>}}/><Tab.Screen name="Categories" component={CategoriesScreen} options={{tabBarIcon:()=><Text>🗂️</Text>}}/><Tab.Screen name="Search" component={SearchScreen} options={{tabBarIcon:()=><Text>🔍</Text>}}/><Tab.Screen name="Progress" component={ProgressScreen} options={{tabBarIcon:()=><Text>📈</Text>}}/><Tab.Screen name="Profile" component={SettingsScreen} options={{tabBarIcon:()=><Text>👤</Text>}}/><Tab.Screen name="Settings" component={SettingsScreen} options={{tabBarButton:()=>null}}/><Tab.Screen name="Scanner" component={ScannerScreen} options={{tabBarButton:()=>null}}/><Tab.Screen name="FoodDetail" component={FoodDetailScreen} options={{tabBarButton:()=>null}}/><Tab.Screen name="MealLog" component={MealLogScreen} options={{tabBarButton:()=>null}}/></Tab.Navigator>)}
export function AppNavigator(){
 const [initial,setInitial]=useState<string|null>(null);
 useEffect(()=>{(async()=>{const done=await hasOnboarded(); setInitial(done?'MainTabs':'Onboarding');})()},[]);
 if(!initial) return null;
 return (<NavigationContainer><Stack.Navigator initialRouteName={initial} screenOptions={{headerShown:false}}><Stack.Screen name="Onboarding" component={OnboardingScreen}/><Stack.Screen name="MainTabs" component={MainTabs}/><Stack.Screen name="Settings" component={SettingsScreen}/><Stack.Screen name="Scanner" component={ScannerScreen}/><Stack.Screen name="FoodDetail" component={FoodDetailScreen}/><Stack.Screen name="MealLog" component={MealLogScreen}/><Stack.Screen name="Search" component={SearchScreen}/></Stack.Navigator></NavigationContainer>)
}
